export type ColleagueGroup = {
  number: 1 | 2 | 3;
  members: readonly string[];
};

const byFirstName = (first: string, second: string) =>
  first.localeCompare(second, "fr", { sensitivity: "base" });

export const COLLEAGUE_GROUPS: readonly ColleagueGroup[] = [
  {
    number: 1,
    members: [
      "Renaud Angles",
      "Issita Arslanov",
      "Erwan Ballan",
      "Jean-Charles Barron",
      "Rachida Ben Khayi",
      "Sébastien Beney",
      "Belinda Benony",
      "Thérèse Beyler",
      "Séverine Body",
      "Michel Borie",
      "Maurizio Campani",
      "Delphine Cateora-Lemonnier",
      "Khadija Chbab",
      "Jeanne Chemin",
      "Michel Cozzi",
      "Magali Durand",
      "Estelle Erkens",
      "Nikky Francius",
      "Lou-Célia Germond",
      "Philippe-Alain Gilleron",
      "Adriana Lecroulant",
      "Franck Lee",
      "Thibaud Marty",
      "Marnia Menacer",
      "Nathalie Novain",
      "Saga Ouiya",
      "Maxence Piat",
      "Dana Radulescu",
      "Adelaide Ragu",
      "Christian Ridez",
      "Riccardo Simonetti",
      "Andréa Soares Ghilardi",
      "Christophe Stezowski",
      "Sivasankari Verdy",
    ].sort(byFirstName),
  },
  {
    number: 2,
    members: [
      "Flora Acquistapace",
      "Audrey Bachter",
      "Antoine Balsarin",
      "Sophie Bedot",
      "Anne-Marie Boulegue",
      "Christine Briand",
      "Gildas Brule",
      "Romain Cherence",
      "Ivan Claisse",
      "Christophe Demarest",
      "Jean-Thomas Douwes",
      "Anthony Dumas",
      "Dominique Durandet",
      "Mickaël Eliaszewicz",
      "Noemie Goke-Lessoua",
      "Claude Griesmar",
      "Yohan Guion",
      "Marta Ilic",
      "Marion Jeannerot",
      "Philippe Klarsfeld",
      "Nathalie Lasgleyzes",
      "Pauline Leberre",
      "Adeline Legris",
      "Jauris Locecere",
      "Jean-Patient Lucenay",
      "Jean-Luc Maurette",
      "Pierre Melquiond",
      "Vicky Muller",
      "Céline Prunneaux",
      "Anissa Redjem",
      "Julien Rivassou",
      "Sophie Savigny",
      "Olivia Serafino",
      "Dudu Shi",
      "Bruno Tacnet",
      "Justine Trillaud",
    ].sort(byFirstName),
  },
  {
    number: 3,
    members: [
      "Alexis Andre",
      "Brigitte Baraza",
      "Cédric Bascunana",
      "Auricio Lemos Bomfim",
      "Antonin Cadoret",
      "Renaud Chevalier",
      "Sonia Codhant",
      "Stéphane Corrado",
      "Neil Dodds",
      "Jérôme Domingos",
      "Emilie Duserre",
      "Carmine Esposito",
      "Robert Xian Feng",
      "Rita Fleury-Leforestier",
      "Arnaud Gaumet",
      "Florian Gautier",
      "Pascal Gourmelin",
      "Katia Hendriks",
      "Zeljka Jovic-Bohet",
      "Jean-Pierre Lardoux",
      "Laurent Lebegue",
      "Cecile Leriche",
      "Evgenii Mislivets",
      "Philippe Mitran",
      "Frédérick Montillet",
      "Gabrielle Piccinno",
      "Adrien Police",
      "Olga Richir",
      "Virginie Rivot",
      "Vincent Sannier",
      "Mehar Shamsudeen",
      "Sepideh Shirzad",
      "Véronique Testard",
      "Maria Toque",
      "Isabelle Toujet",
    ].sort(byFirstName),
  },
];
